//plugins {
//    id 'org.springframework.boot' version '3.5.4'
//    id 'io.spring.dependency-management' version '1.1.4'
//    id 'java'
//}

apply plugin: 'org.springframework.boot'

dependencies {
	implementation project(':security')
	implementation project(':reactive-web')
    implementation project(':jwt')
	implementation project(':r2dbc-postgresql')
    implementation project(':model')
    implementation project(':usecase')
    implementation 'org.reactivecommons.utils:object-mapper:0.1.0'
    implementation 'org.springframework.boot:spring-boot-starter'
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
}

jar {
    // To disable the *-plain.jar
    enabled = false
}

bootJar {
    archiveFileName = 'autenticacion-service.jar'
    mainClass = 'co.com.camilo.MainApplication'
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}